### ISSUE TITLE
Does not work with official 0.11 API

### ISSUE THREAD

**Issue by slime73** [Nixola/PlayQueue#1]
The queue APIs merged into 0.11's code are `love.audio.newQueueableSource(rate, ...)`, `Source:queue`, and `Source:getFreeBufferCount` instead of `love.audio.newSource(rate, ...)`, `Source:queueData`, and `Source:isQueueable` respectively.

**Comment by Nixola** [comment]
It wasn't yet supposed to, since I only learned it got merged while I was in bed =P
Anyway, commit a78862814d9649300c85d3a1d5e576202143da0f solved this, I think. Can I mark what commit did that? Is it automatic since I mentioned it? I don't know what to do
Do I close it or do I mark it as solved somehow? I've never used Github issues properly
